name: Ajit Johnson Nirmal
description: Cancer Geneticist,<a href="https://scholar.harvard.edu/ajitjohnson"> Harvard University </a>| Voicing for evidence based policies to preserve our species for another million years.
meta_description: "Cancer Geneticist @ Harvard University"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'https://ajitjohnson.com'
google_analytics: 'UA-87347639-1'
disqus: true
disqus_shortname: 'ajitjohnson-com'

# Details for the RSS feed generator
url:            'https://ajitjohnson.com'
author:         'Ajit Johnson Nirmal'
authorTwitter:  'ajitjohnson_n'

permalink:       /:title/

jekyll_ga:
  service_account_email: n.ajitjohnson@gmail.com   # service account email address
  key_file: ajitjohnson-analytics-08a77bf88715.p12  # service account private key file
  key_secret: notasecret    # service account private key's password
  profileID: ga:133666144        # profile ID
  start: 5/27/1988        # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment:                  # optional
  filters:                  # optional
  sort: false                # Sort posts by this metric

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
