# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ajit Johnson Nirmal
tagline:          'Cancer Geneticist @ Harvard University'
description:      'Voicing for evidence based policies to preserve our species for another million years.'
url:              http://ajitjohnson.github.io
baseurl:          /

author:
  name:           'Ajit Johnson Nirmal'
  url:            https://twitter.com/ajitjohnson_n

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ajitjohnson/ajitjohnson.github.io
